"""novas entidades para teste de aplicacao

Revision ID: 34538850aabc
Revises: a4aedeb41c64
Create Date: 2026-09-18 17:21:49.798714

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '34538850aabc'
down_revision: Union[str, Sequence[str], None] = 'a4aedeb41c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employees',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('READY', 'IN_PROGRESS', 'TESTING', 'DONE', name='status'),
            nullable=False,
        ),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['creator_id'],
            ['employees.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('company', sa.String(), nullable=False),
        sa.Column(
            'translate_from',
            sa.Enum(
                'PORTUGUESE',
                'ENGLISH',
                'SPANISH',
                'GERMAN',
                'ITALIAN',
                'FRANCH',
                'OTHER',
                name='translations',
            ),
            nullable=False,
        ),
        sa.Column(
            'translate_to',
            sa.Enum(
                'PORTUGUESE',
                'ENGLISH',
                'SPANISH',
                'GERMAN',
                'ITALIAN',
                'FRANCH',
                'OTHER',
                name='translations',
            ),
            nullable=False,
        ),
        sa.Column('observations', sa.String(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['employee_id'],
            ['employees.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'stages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('freelancer_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('READY', 'IN_PROGRESS', 'TESTING', 'DONE', name='status'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['freelancer_id'],
            ['employees.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'project_stages',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('stage_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
        ),
        sa.ForeignKeyConstraint(
            ['stage_id'],
            ['stages.id'],
        ),
        sa.PrimaryKeyConstraint('project_id', 'stage_id'),
    )
    op.create_table(
        'request_files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('request_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['request_id'],
            ['requests.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'stage_files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('stage_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['stage_id'],
            ['stages.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'username', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'password', sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
        sa.UniqueConstraint(
            'email',
            name=op.f('users_email_key'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            'username',
            name=op.f('users_username_key'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table('stage_files')
    op.drop_table('request_files')
    op.drop_table('project_stages')
    op.drop_table('stages')
    op.drop_table('requests')
    op.drop_table('projects')
    op.drop_table('employees')
    # ### end Alembic commands ###
