"""adiciona novo atributo para stages

Revision ID: 562e8047a1f2
Revises: bc003363b4ba
Create Date: 2026-09-24 19:06:01.112414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562e8047a1f2'
down_revision: Union[str, Sequence[str], None] = 'bc003363b4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'name')
    # ### end Alembic commands ###
