"""adiciona a relacao projeto e etapa

Revision ID: b219a1360ee8
Revises: b94c0423bc60
Create Date: 2026-09-19 08:51:32.987942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b219a1360ee8'
down_revision: Union[str, Sequence[str], None] = 'b94c0423bc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
