"""adiciona atributo name para stages

Revision ID: b608d6cbc575
Revises: e1580401a199
Create Date: 2026-09-28 17:49:59.097175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b608d6cbc575'
down_revision: Union[str, Sequence[str], None] = 'e1580401a199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'name')
    # ### end Alembic commands ###
