"""melhora a relacao entre projeto e etapa

Revision ID: bc003363b4ba
Revises: b94c0423bc60
Create Date: 2026-09-19 09:46:03.399929

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc003363b4ba'
down_revision: Union[str, Sequence[str], None] = 'b94c0423bc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'requests', 'company', existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        'requests', 'observations', existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'requests', 'observations', existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        'requests', 'company', existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
