"""modifica relacionamento entre path e stage

Revision ID: e1580401a199
Revises: 7636b3bf96a6
Create Date: 2026-09-28 17:27:24.694381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1580401a199'
down_revision: Union[str, Sequence[str], None] = '7636b3bf96a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path_stages',
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['paths.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('path_id', 'stage_id')
    )
    op.drop_constraint(op.f('fk_stages_path_id_paths'), 'stages', type_='foreignkey')
    op.drop_column('stages', 'path_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('path_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_stages_path_id_paths'), 'stages', 'paths', ['path_id'], ['id'])
    op.drop_table('path_stages')
    # ### end Alembic commands ###
